# docker-compose.yml
version: '3'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - database
    env_file:
      - database.env
        
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
     # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
